### ISSUE TITLE
Generate a "man" from the application console

### ISSUE THREAD

**Issue by mpoiriert** [mpoiriert/draw#209]
We want to be able to "export" a documentation for all the command available in a application.

A standard supported format easy to search would be great or a stand alone html.

If something already exists we could simply integrate it the the framework extra bundle.

Other wise it need to be in the console packages and integrate in the framework extra bundle.

**Comment by olarno** [comment]
Two different way to find the correct solution:

- Look how work the command `bin/console list`, to see how we can handle all the command.

- Look in `Symfony\Component\Console\Application` the method `all($namespace)` allows us to retrieve all the commands registered in the given namespace.

**Comment by olarno** [comment]
Second way is better, more information for each command. 

I will clean my code, but just FYI, I retrieve all command in the Application (native to sf or custom), then we are able to manage which information we want return into a json file. 

We can imagine different level of documentation, `name` `description` `options` etc..

**Comment by mpoiriert** [comment]
Good, I'll see more in detail when your PR is done.

**Comment by mpoiriert** [comment]
Command is available trough console component named 'draw:console:generate-documentation'.

Will generate in Markdown format base on the builtin help format md command.
